### PR TITLE
let the route decide if the navigation bar is shown or not

### LINKED ISSUE #6: Is there any way to hide navigation bar after initial route
I know the showNavigationBar prop with the ExNavigator component but I need to hide navbar after first route. Is there any way ? 

Thanks

### PR DESCRIPTION
**Pull request by despairblue**
fixes #6

Or rather works around https://github.com/facebook/react-native/issues/3754 by vendoring NavigatorNavigationBar.

### CODE REVIEW

**Comment by ide** [comment]
I don't totally understand what this PR does but I want ExNavigator to be much more general and maintainable. Specifically, a big file like the NavigationBar shouldn't be vendors if we can help it, and we especially shouldn't modify it. We don't have the bandwidth to take on the maintenance cost -- the `renderNavigationBar` prop exists so people can provide their own navigation bars.

**Comment by despairblue** [comment]
Agreed. My problem was that I had to modify `NavigatorNavigationBar`, since wrapping it breaks it. Haven't thought about bundling it with my app and supplying it via the `renderNavigationBar` prop. That should work perfectly. 

The modified `NavigatorNavigationBar` could even be provided as a separate npm module, that would also solve #6.

**Comment by ide** [comment]
We wrap the NavigationBar in one of our own products and had to define a couple of imperative public methods and forward them to a NavigationBar we had wrapped. Perhaps you'd be able to do the same.

**Comment by despairblue** [comment]
Nevermind, I think, it will work after implementing `updateProgress`, which is called by `Navigator`.

Leaving the rest here in case someone else trips over this...

> :confused: Maybe I'm really doing something wrong and can't see the forest for the trees.
> 
> I took the Navigator example for the UIExplorer and the only things I changed were:
> - [wrapping the Navigator.NavigationBar in another component, passing the same props through](https://gist.github.com/despairblue/fb5eb3674f5d56183fc8#file-navigationbarsample2-js-L92)
>   - [the condition always evaluates to `true`, so that should not be the cause for the problem](https://gist.github.com/despairblue/fb5eb3674f5d56183fc8#file-navigationbarsample2-js-L92)
> - [logging the current route to the console](https://gist.github.com/despairblue/fb5eb3674f5d56183fc8#file-navigationbarsample2-js-L92)
> 
> And as can be seen in the gif in https://github.com/facebook/react-native/issues/3754, just by wrapping `Navigator.NavigationBar` the NavigationBar is always off by one route and only for the first render pass. This completely flabbergasts me :worried:
> 
> I even stepped through the execution 'till https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js#L157 and as far as I can inspect the `components`-object, it seems to be exactly the same compared to not wrapping `Navigator.NavigationBar`.
> 
> I'm at a complete loss here.

**Comment by ide** [comment]
Thanks for the follow-up! BTW if you need ExNavigator to make small modifications that let you flexibly address your use case we are happy to review those PRs and make ExNavigator more broadly useful. One way I think of it is: how can we make the best programmers more productive? and then everyone else can work on becoming the best programmers.

**Pull request closed without merging**
