### PR TITLE
pass navigator to augmentScene as well.

### PR DESCRIPTION
**Pull request by chirag04**
at times it is useful to look at the route stack while augmenting a scene. This PR passes navigator to augmentScene for that.

### CODE REVIEW

**Comment by cancan101** [comment]
Any updates on this? /CC @brentvatne

**Comment by cancan101** [comment]
Bump /CC @ide

**Comment by cancan101** [comment]
bump

**Comment by Ape-Bite-Apple** [comment]
how to hidden?

**Pull request closed without merging**
